"""``strata serve`` — the local web app.

Standard library only, bound to loopback by default. Routes:

    GET /                     the single-page interface
    GET /api/health           version, and which networks are loaded
    GET /api/ask?q=&k=        the full result as JSON
    GET /api/stream?q=&k=     the same, preceded by server-sent progress events
    GET /api/export?q=&format=md|bib|json

``/api/stream`` exists because a real question takes several seconds — a PubMed
search, then a fetch, then grading — and a spinner that says nothing for six
seconds reads as a hang. The stream reports each stage as it starts, so the wait
is legible.

Nothing is stored: no query log, no result cache beyond the shared PubMed cache
in :mod:`strata.cache`, no cookies. The server binds to 127.0.0.1 unless told
otherwise, and refuses to bind elsewhere without an explicit acknowledgement,
because this has no authentication and is not built to face a network.
"""
from __future__ import annotations

import json
import queue
import threading
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from . import __version__
from .query import ask
from .synthesize import key_finding
from .ui import PAGE

MAX_K = 20
MAX_QUESTION = 400


def _enrich(payload: dict) -> dict:
    """Add the display-ready fields the front end needs.

    Kept here rather than in :class:`strata.query.Evidence` so the library's own
    JSON stays a faithful description of the appraisal, without presentation
    concerns leaking into it.
    """
    for src, ev in zip(payload.get("sources", []), payload.get("_evidence", [])):
        article, g = ev.article, ev.grade
        src["journal"] = article.journal
        src["finding"] = key_finding(article.abstract)
        if g.effect is not None and g.effect.has_interval:
            src["effect_est"] = g.effect.estimate
            src["effect_ci"] = [g.effect.ci_low, g.effect.ci_high]
            src["effect_is_ratio"] = g.effect.is_ratio
    payload.pop("_evidence", None)
    return payload


def build_payload(result) -> dict:
    payload = result.as_dict()
    payload["_evidence"] = result.evidence
    return _enrich(payload)


# ------------------------------------------------------------------- exports

def to_markdown(result) -> str:
    lines = [f"# {result.question}", "",
             f"**Certainty: {result.body.overall_strength}** — {result.body.summary}", ""]
    for c in result.body.caveats:
        lines.append(f"> ⚠ {c}")
    if result.body.caveats:
        lines.append("")
    if result.consensus is not None and result.consensus.direction != "insufficient":
        lines += [f"**Consensus.** {result.consensus.summary}", ""]
    if result.pooled is not None:
        lines += [f"**Indicative pooling.** {result.pooled.format()}. "
                  f"Not a systematic review — one search, pooled for orientation.", ""]

    lines += ["## Sources", ""]
    for i, e in enumerate(result.evidence, 1):
        a, g = e.article, e.grade
        flag = " **[RETRACTED]**" if g.retracted else (
            " **[expression of concern]**" if g.concern else "")
        lines.append(f"{i}. **{a.title}**{flag}  ")
        lines.append(f"   *{g.label} · {g.strength} certainty · "
                     f"{a.journal or 'n.k.'} {a.year or 'n.d.'}*  ")
        finding = key_finding(a.abstract)
        if finding:
            lines.append(f"   {finding}  ")
        bits = []
        if g.effect is not None:
            bits.append(g.effect.format())
        if g.sample_size:
            bits.append(f"n = {g.sample_size:,}")
        if g.safeguards:
            bits.append("reports " + ", ".join(g.safeguards))
        if bits:
            lines.append(f"   {' · '.join(bits)}  ")
        for d in g.downgrades:
            lines.append(f"   ↓ {d.name}: {d.reason}  ")
        lines.append(f"   <{a.url}>")
        lines.append("")

    lines += ["---", "",
              f"Generated by Strata {__version__} from a PubMed search "
              f"(`{result.query}`). Decision support, not medical advice."]
    return "\n".join(lines)


def to_bibtex(result) -> str:
    """BibTeX for the cited papers, with retractions marked in a note field."""
    out = []
    for i, e in enumerate(result.evidence, 1):
        a, g = e.article, e.grade
        first = (a.authors[0].split()[0] if a.authors else "anon").lower()
        key = f"{_ascii(first)}{a.year or 'nd'}pmid{a.pmid}"
        fields = [
            ("title", a.title.rstrip(".")),
            ("author", " and ".join(a.authors[:12]) or "Anonymous"),
            ("journal", a.journal),
            ("year", str(a.year) if a.year else ""),
            ("volume", a.volume), ("number", a.issue), ("pages", a.pages),
            ("doi", a.doi), ("url", a.url),
            ("note", _bib_note(g)),
        ]
        body = ",\n".join(f"  {k} = {{{_bib_escape(v)}}}"
                          for k, v in fields if v)
        out.append(f"@article{{{key},\n{body}\n}}")
    return "\n\n".join(out) + "\n"


def _bib_note(g) -> str:
    bits = [f"{g.label}; {g.strength} certainty (Strata grading)"]
    if g.retracted:
        bits.insert(0, "RETRACTED PUBLICATION")
    elif g.concern:
        bits.insert(0, "Expression of concern issued")
    return ". ".join(bits)


def _bib_escape(v: str) -> str:
    return str(v).replace("\\", r"\textbackslash{}").replace("{", r"\{") \
                 .replace("}", r"\}").replace("&", r"\&").replace("%", r"\%")


def _ascii(s: str) -> str:
    return "".join(ch for ch in s if ch.isalnum()) or "anon"


# ------------------------------------------------------------------- handler

def _handler_class(k_default: int):
    class Handler(BaseHTTPRequestHandler):
        server_version = f"Strata/{__version__}"
        protocol_version = "HTTP/1.1"

        def log_message(self, *args):
            pass                                  # no request log: nothing is stored

        # -- helpers -------------------------------------------------------
        def _send(self, body: bytes, ctype: str, code: int = 200, **headers):
            self.send_response(code)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(body)))
            self.send_header("X-Content-Type-Options", "nosniff")
            self.send_header("Referrer-Policy", "no-referrer")
            for k, v in headers.items():
                self.send_header(k.replace("_", "-"), v)
            self.end_headers()
            try:
                self.wfile.write(body)
            except (BrokenPipeError, ConnectionResetError):
                pass

        def _json(self, obj, code: int = 200):
            self._send(json.dumps(obj, default=str).encode("utf-8"),
                       "application/json; charset=utf-8", code)

        def _params(self):
            u = urllib.parse.urlparse(self.path)
            q = urllib.parse.parse_qs(u.query)
            question = (q.get("q") or [""])[0].strip()[:MAX_QUESTION]
            try:
                k = int((q.get("k") or [str(k_default)])[0])
            except ValueError:
                k = k_default
            return u.path.rstrip("/") or "/", question, max(1, min(k, MAX_K)), q

        # -- routes --------------------------------------------------------
        def do_GET(self):
            path, question, k, raw = self._params()
            if path == "/":
                return self._send(PAGE.encode("utf-8"), "text/html; charset=utf-8")
            if path == "/api/health":
                return self._health()
            if path == "/api/ask":
                return self._ask(question, k)
            if path == "/api/stream":
                return self._stream(question, k)
            if path == "/api/export":
                return self._export(question, k, (raw.get("format") or ["md"])[0])
            return self._json({"error": "not found"}, 404)

        def _health(self):
            try:
                from . import nn
                nets = nn.available()
            except Exception:
                nets = {}
            self._json({"status": "ok", "version": __version__, "networks": nets})

        def _ask(self, question, k):
            if not question:
                return self._json({"error": "Ask a clinical question."}, 400)
            try:
                return self._json(build_payload(ask(question, k=k)))
            except Exception as exc:
                return self._json({"error": str(exc)}, 500)

        def _export(self, question, k, fmt):
            if not question:
                return self._json({"error": "Ask a clinical question."}, 400)
            try:
                result = ask(question, k=k)
            except Exception as exc:
                return self._json({"error": str(exc)}, 500)

            stem = "".join(ch if ch.isalnum() else "-"
                           for ch in question.lower())[:60].strip("-") or "strata"
            if fmt == "json":
                body = json.dumps(result.as_dict(), indent=2, default=str)
                ctype, ext = "application/json; charset=utf-8", "json"
            elif fmt in ("bib", "bibtex"):
                body, ctype, ext = to_bibtex(result), "application/x-bibtex", "bib"
            else:
                body, ctype, ext = to_markdown(result), "text/markdown; charset=utf-8", "md"
            self._send(body.encode("utf-8"), ctype,
                       Content_Disposition=f'attachment; filename="{stem}.{ext}"')

        def _stream(self, question, k):
            """Server-sent events: one per pipeline stage, then the result."""
            if not question:
                return self._json({"error": "Ask a clinical question."}, 400)

            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream; charset=utf-8")
            self.send_header("Cache-Control", "no-cache, no-transform")
            self.send_header("Connection", "close")
            self.send_header("X-Accel-Buffering", "no")
            self.end_headers()

            events: queue.Queue = queue.Queue()

            def progress(stage, message):
                events.put(("stage", {"stage": stage, "message": message}))

            def work():
                try:
                    result = ask(question, k=k, progress=progress)
                    events.put(("result", build_payload(result)))
                except Exception as exc:
                    events.put(("failed", {"error": str(exc)}))
                finally:
                    events.put((None, None))

            worker = threading.Thread(target=work, daemon=True)
            worker.start()

            try:
                while True:
                    kind, data = events.get()
                    if kind is None:
                        break
                    chunk = (f"event: {kind}\n"
                             f"data: {json.dumps(data, default=str)}\n\n")
                    self.wfile.write(chunk.encode("utf-8"))
                    self.wfile.flush()
            except (BrokenPipeError, ConnectionResetError):
                pass                              # the user navigated away
            finally:
                # The worker is a daemon and will finish on its own; the close
                # here just stops us writing into a dead socket.
                self.close_connection = True

    return Handler


def serve(port: int = 8600, host: str = "127.0.0.1", *, k: int = 8,
          allow_remote: bool = False) -> None:
    if host not in ("127.0.0.1", "localhost", "::1") and not allow_remote:
        raise SystemExit(
            f"Refusing to bind {host}: Strata has no authentication and is not "
            f"built to face a network. Pass --allow-remote if you are certain.")

    httpd = ThreadingHTTPServer((host, port), _handler_class(k))
    httpd.daemon_threads = True
    print(f"Strata {__version__} running on http://{host}:{port}   (ctrl-c to stop)")
    try:
        from . import nn
        loaded = [n for n, ok in nn.available().items() if ok]
        print("networks: " + (", ".join(loaded) if loaded
                              else "none trained — rule-based grading only"))
    except Exception:
        pass
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped")
    finally:
        httpd.server_close()
